"""Report message formatter.

Formats LLM-generated content into structured Telegram report templates
matching the format defined in 02_AGENT_INSTRUCTIONS.md section 5.
"""

from __future__ import annotations

from datetime import datetime

SEPARATOR = "━" * 21

DISCLAIMER = (
    f"{SEPARATOR}\n"
    "⚠️ DISCLAIMER\n"
    "Đây là phân tích tham khảo, không phải tư vấn tài chính.\n"
    "Mọi quyết định đầu tư là trách nhiệm cá nhân."
)


class ReportFormatter:
    """Format LLM content into structured Telegram report messages."""

    def format(self, report_type: str, now: datetime, llm_content: str) -> str:
        """Format report based on type.

        Args:
            report_type: "morning" or "evening".
            now: Current datetime in JST.
            llm_content: Content generated by LLM.

        Returns:
            Formatted report string ready for Telegram.
        """
        if report_type == "morning":
            return self._format_morning(now, llm_content)
        return self._format_evening(now, llm_content)

    def _format_morning(self, now: datetime, llm_content: str) -> str:
        """Format morning pre-market brief."""
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M JST")

        header = (
            f"🌅 KAI-FINA | Pre-Market Brief\n"
            f"📅 {date_str} | ⏰ {time_str}\n"
            f"{SEPARATOR}"
        )

        return f"{header}\n\n{llm_content}\n\n{DISCLAIMER}"

    def _format_evening(self, now: datetime, llm_content: str) -> str:
        """Format evening end-of-day report."""
        date_str = now.strftime("%Y-%m-%d")

        header = (
            f"🌙 KAI-FINA | End-of-Day Report\n"
            f"📅 {date_str} | Phiên giao dịch Tokyo đã đóng cửa\n"
            f"{SEPARATOR}"
        )

        return f"{header}\n\n{llm_content}\n\n{DISCLAIMER}"
